-- Pembuatan tabel
CREATE TABLE IF NOT EXISTS public.loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  borrower_name TEXT NOT NULL,
  book_title TEXT NOT NULL,
  loan_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE NOT NULL,
  return_date DATE,
  status VARCHAR(50) NOT NULL DEFAULT 'Dipinjam',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;

-- Akses CRUD ke public/anon key
DROP POLICY IF EXISTS "Allow public full access on loans" ON public.loans;

CREATE POLICY "Allow public full access on loans" 
ON public.loans 
FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Dummy
INSERT INTO public.loans (borrower_name, book_title, loan_date, due_date, return_date, status)
VALUES
  ('Budi Santoso', 'Clean Code: A Handbook of Agile Software Craftsmanship', '2026-09-20', '2026-09-27', '2026-09-26', 'Kembali'),
  ('Siti Rahma', 'JavaScript: The Good Parts', '2026-09-15', '2026-09-22', NULL, 'Terlambat'),
  ('Andi Pratama', 'Design Patterns: Elements of Reusable Object-Oriented Software', '2026-09-28', '2026-10-05', NULL, 'Dipinjam'),
  ('Dewi Lestari', 'Introduction to Algorithms (CLRS)', '2026-09-10', '2026-09-17', NULL, 'Terlambat'),
  ('Rian Hidayat', 'You Don''t Know JS Yet', '2026-09-29', '2026-10-06', NULL, 'Dipinjam');
